[package]
name = "eq-item-bot"
version = "0.1.0"
authors = ["Cory Kolbeck <ckolbeck@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.7"
regex = "1"
percent-encoding = "2.1.0"
scraper = "0.11.0"
reqwest = "0.9.24"
select = "0.4.3"
